import fs from 'fs'
import path from 'path'
import type { IExtensionContext } from 'heybox-mod-api'

const GAME_ID = 262060
const GAME_NAME = 'Darkest Dungeon'
const EXECUTABLE = '_windows/win64/Darkest.exe'
const MODS_DIR = 'mods'
const MOD_TYPE_ID = 'darkest-dungeon-mod'
const MOD_TYPE_PRIORITY = 25
const INSTALLER_PRIORITY = 50
const NO_PROJECT_INSTALLER_PRIORITY = 25
const PROJECT_XML = 'project.xml'
const DEFAULT_MOD_NAME = 'darkest_dungeon_mod'
const HERO_PORTRAIT_SUFFIX = '_portrait_roster.png'
const HEROES_ROOT = 'heroes'
const PROJECT_TEMPLATE = `<?xml version="1.0" encoding="utf-8"?>
<project>
    <PreviewIconFile>preview_icon.png</PreviewIconFile>
    <ItemDescriptionShort/>
    <ModDataPath>{{modPath}}</ModDataPath>
    <Title>{{title}}</Title>
    <Language>english</Language>
    <UpdateDetails/>
    <Visibility>public</Visibility>
    <UploadMode>direct_upload</UploadMode>
    <VersionMajor>1</VersionMajor>
    <VersionMinor>0</VersionMinor>
    <TargetBuild>0</TargetBuild>
    <Tags>
    </Tags>
    <ItemDescription>File generated by Heybox</ItemDescription>
</project>`
const DARKEST_DUNGEON_DIRECTORIES = new Set([
  'activity_log',
  'audio',
  'campaign',
  'colours',
  'curios',
  'cursors',
  'dungeons',
  'effects',
  'fe_flow',
  'fonts',
  'fx',
  'game_over',
  'heroes',
  'inventory',
  'loading_screen',
  'localization',
  'loot',
  'maps',
  'modes',
  'monsters',
  'overlays',
  'panels',
  'props',
  'raid',
  'raid_results',
  'scripts',
  'scrolls',
  'shaders',
  'shared',
  'trinkets',
  'upgrades',
  'user_information',
])

type FileEntry = {
  source: string
  segments: string[]
}

type ProjectInfo = {
  entry: FileEntry
  rootSegments: string[]
}

type InstallOptions = {
  sourcePathByFile?: Record<string, string>
}

type CopyInstruction = {
  type: 'copy'
  source: string
  destination: string
}

type GenerateFileInstruction = {
  type: 'generatefile'
  data: string
  destination: string
}

type InstallInstruction = CopyInstruction | GenerateFileInstruction

function normalizeArchivePath(filePath: string): string | null {
  const normalized = String(filePath || '')
    .replace(/\\/g, '/')
    .replace(/^\/+/, '')
    .replace(/^(\.\/)+/g, '')
    .replace(/\/+/g, '/')
    .trim()

  if (!normalized || normalized.endsWith('/')) return null
  if (normalized.startsWith('/') || /^[A-Za-z]:\//.test(normalized)) return null

  const segments = normalized.split('/').filter(Boolean)
  if (segments.some((segment) => segment === '.' || segment === '..')) return null

  return segments.join('/')
}

function normalizeFiles(files: string[]): FileEntry[] {
  return files
    .map((file) => {
      const source = normalizeArchivePath(file)
      if (!source) return null
      return {
        source,
        segments: source.split('/'),
      }
    })
    .filter(Boolean) as FileEntry[]
}

function archiveBaseName(entry: FileEntry): string {
  return entry.segments[entry.segments.length - 1] || ''
}

function isProjectXml(entry: FileEntry): boolean {
  return archiveBaseName(entry).toLowerCase() === PROJECT_XML
}

function hasFileExtension(entry: FileEntry): boolean {
  return path.extname(archiveBaseName(entry)) !== ''
}

function findProjectFiles(entries: FileEntry[]): ProjectInfo[] {
  return entries
    .filter(isProjectXml)
    .map((entry) => ({
      entry,
      rootSegments: entry.segments.slice(0, -1),
    }))
}

function startsWithSegments(entry: FileEntry, rootSegments: string[]): boolean {
  if (entry.segments.length <= rootSegments.length) return false
  return rootSegments.every((segment, index) => entry.segments[index] === segment)
}

function getRelativeSegments(entry: FileEntry, rootSegments: string[]): string[] | null {
  if (!startsWithSegments(entry, rootSegments)) return null
  return entry.segments.slice(rootSegments.length)
}

function getSingleWrapperRoot(entries: FileEntry[]): string | null {
  const roots = new Set<string>()
  for (const entry of entries) {
    const root = entry.segments[0]
    if (!root || entry.segments.length < 2) return null
    roots.add(root)
    if (roots.size > 1) return null
  }
  return [...roots][0] || null
}

function isWrappedProject(entries: FileEntry[], project: ProjectInfo): boolean {
  return project.rootSegments.length > 0
    && entries.some((entry) => entry !== project.entry && startsWithSegments(entry, project.rootSegments))
}

function allEntriesUnderProjectRoots(entries: FileEntry[], projects: ProjectInfo[]): boolean {
  return entries.every((entry) => projects.some((project) => startsWithSegments(entry, project.rootSegments)))
}

function sanitizeFolderName(context: IExtensionContext, name: string, fallback = DEFAULT_MOD_NAME): string {
  return context.api.util.sanitizeFilename(name, fallback).replace(/\./g, '_')
}

function sanitizePathSegment(context: IExtensionContext, name: string): string {
  return context.api.util.sanitizeFilename(name, '_')
}

function toDestinationPath(context: IExtensionContext, segments: string[]): string {
  return path.join(...segments.map((segment) => sanitizePathSegment(context, segment)))
}

function readXmlValue(value: unknown): string | undefined {
  if (typeof value === 'string') return value
  if (Array.isArray(value)) return readXmlValue(value[0])
  return undefined
}

function readProjectTitle(parsedXml: Record<string, unknown>): string | undefined {
  return readXmlValue((parsedXml as any)?.project?.Title)?.trim()
}

function getProjectSourcePath(projectFile: string, stagingPath?: string, options?: InstallOptions): string | undefined {
  return options?.sourcePathByFile?.[projectFile]
    || (stagingPath ? path.join(stagingPath, ...projectFile.split('/')) : undefined)
}

async function readProjectTitleFromFile(
  context: IExtensionContext,
  projectFile: string,
  stagingPath?: string,
  options?: InstallOptions
): Promise<string> {
  const sourcePath = getProjectSourcePath(projectFile, stagingPath, options)
  if (!sourcePath) {
    throw new Error('Darkest Dungeon installer requires stagingPath to read project.xml')
  }

  const fileData = await fs.promises.readFile(sourcePath, { encoding: 'utf8' })
  const parsed = await context.api.util.fileParseApi.parseXmlToObject(fileData)
  const title = readProjectTitle(parsed)
  if (!title) {
    throw new Error('project.xml must contain a non-empty Title field when installing loose files')
  }
  return title
}

async function findGame(context: IExtensionContext): Promise<string | undefined> {
  const game = await context.api.util.GameStoreHelper.findByAppId(GAME_ID)
  return game?.gamePath
}

function testDarkestDungeonMod(files: string[], gameId: number | string): { supported: boolean; requiredFiles: string[] } {
  return {
    supported: Number(gameId) === GAME_ID && findProjectFiles(normalizeFiles(files)).length > 0,
    requiredFiles: [],
  }
}

function isKnownGameDirectory(segment: string): boolean {
  return DARKEST_DUNGEON_DIRECTORIES.has(segment.toLowerCase())
}

function findKnownGameDirectoryIndex(entry: FileEntry): number {
  return entry.segments.findIndex(isKnownGameDirectory)
}

function isHeroPortrait(entry: FileEntry): boolean {
  return archiveBaseName(entry).toLowerCase().endsWith(HERO_PORTRAIT_SUFFIX)
}

function testDarkestDungeonNoProjectMod(files: string[], gameId: number | string): { supported: boolean; requiredFiles: string[] } {
  const entries = normalizeFiles(files)
  const supported = Number(gameId) === GAME_ID
    && findProjectFiles(entries).length === 0
    && entries.some((entry) => isHeroPortrait(entry) || findKnownGameDirectoryIndex(entry) >= 0)

  return {
    supported,
    requiredFiles: [],
  }
}

function buildWrappedInstructions(entries: FileEntry[]): CopyInstruction[] {
  return entries.map((entry) => ({
    type: 'copy',
    source: entry.source,
    destination: path.join(...entry.segments),
  }))
}

async function buildLooseInstructions(
  context: IExtensionContext,
  entries: FileEntry[],
  projects: ProjectInfo[],
  stagingPath?: string,
  options?: InstallOptions
): Promise<InstallInstruction[]> {
  const instructions: InstallInstruction[] = []
  const assigned = new Set<string>()
  const projectTargets = new Map<ProjectInfo, string>()

  for (const project of projects) {
    if (project.rootSegments.length === 0) continue
    const wrappedEntries = entries.filter((entry) => startsWithSegments(entry, project.rootSegments))
    if (wrappedEntries.length <= 1) continue

    const targetRoot = sanitizeFolderName(context, await readProjectTitleFromFile(context, project.entry.source, stagingPath, options))
    projectTargets.set(project, targetRoot)
    for (const entry of wrappedEntries) {
      const relativeSegments = getRelativeSegments(entry, project.rootSegments)
      if (!relativeSegments?.length) continue
      instructions.push({
        type: 'copy',
        source: entry.source,
        destination: path.join(targetRoot, toDestinationPath(context, relativeSegments)),
      })
      assigned.add(entry.source)
    }
  }

  const looseProject = projects.find((project) => project.rootSegments.length === 0)
  if (looseProject) {
    const targetRoot = sanitizeFolderName(context, await readProjectTitleFromFile(context, looseProject.entry.source, stagingPath, options))
    for (const entry of entries) {
      if (assigned.has(entry.source)) continue
      instructions.push({
        type: 'copy',
        source: entry.source,
        destination: path.join(targetRoot, toDestinationPath(context, entry.segments)),
      })
      assigned.add(entry.source)
    }
  } else if (projects.length === 1 && projectTargets.has(projects[0])) {
    const targetRoot = projectTargets.get(projects[0])!
    for (const entry of entries) {
      if (assigned.has(entry.source)) continue
      instructions.push({
        type: 'copy',
        source: entry.source,
        destination: path.join(targetRoot, toDestinationPath(context, entry.segments)),
      })
      assigned.add(entry.source)
    }
  }

  const unassigned = entries.filter((entry) => !assigned.has(entry.source))
  if (unassigned.length > 0) {
    throw new Error('Darkest Dungeon installer cannot assign loose files when multiple project.xml files are present')
  }

  return instructions
}

async function installDarkestDungeonMod(
  context: IExtensionContext,
  files: string[],
  stagingPath?: string,
  options?: InstallOptions
): Promise<{ instructions: InstallInstruction[]; modType: string }> {
  const entries = normalizeFiles(files)
  const projects = findProjectFiles(entries)
  if (projects.length === 0) {
    return { instructions: [], modType: MOD_TYPE_ID }
  }

  const wrapperRoot = getSingleWrapperRoot(entries)
  if (wrapperRoot && projects.every((project) => project.rootSegments[0] === wrapperRoot)) {
    return { instructions: buildWrappedInstructions(entries), modType: MOD_TYPE_ID }
  }

  if (projects.length > 1 && projects.every((project) => isWrappedProject(entries, project)) && allEntriesUnderProjectRoots(entries, projects)) {
    return { instructions: buildWrappedInstructions(entries), modType: MOD_TYPE_ID }
  }

  return {
    instructions: await buildLooseInstructions(context, entries, projects, stagingPath, options),
    modType: MOD_TYPE_ID,
  }
}

function firstWrapperRoot(entries: FileEntry[]): string | undefined {
  return entries.find((entry) => entry.segments.length > 1)?.segments[0]
}

function inferHeroName(portrait: FileEntry): string | undefined {
  const portraitDir = portrait.segments.slice(0, -1)
  const rawName = portraitDir[portraitDir.length - 1]
  return rawName?.replace(/_[A-Z]/g, '')
}

function inferNoProjectModName(context: IExtensionContext, entries: FileEntry[], stagingPath?: string): string {
  const portrait = entries.find(isHeroPortrait)
  const candidate = firstWrapperRoot(entries)
    || (portrait ? inferHeroName(portrait) : undefined)
    || (stagingPath ? path.basename(stagingPath, '.installing') : undefined)
    || DEFAULT_MOD_NAME
  return sanitizeFolderName(context, candidate)
}

function buildProjectXml(title: string): string {
  return PROJECT_TEMPLATE
    .replace('{{title}}', title)
    .replace('{{modPath}}', path.join(MODS_DIR, title))
}

function sameParentDirectory(lhs: FileEntry, rhs: FileEntry): boolean {
  return lhs.segments.slice(0, -1).join('/') === rhs.segments.slice(0, -1).join('/')
}

function buildHeroNoProjectEntries(context: IExtensionContext, entries: FileEntry[]): CopyInstruction[] {
  const onlyFiles = entries.filter(hasFileExtension)
  const portraits = onlyFiles.filter(isHeroPortrait)
  const instructions: CopyInstruction[] = []
  const assigned = new Set<string>()

  for (const portrait of portraits) {
    const portraitDir = portrait.segments.slice(0, -1)
    const heroName = inferHeroName(portrait)
    if (!heroName) continue

    const heroSuffix = (portraitDir[portraitDir.length - 1] || '').slice(-2)
    const heroPath = [HEROES_ROOT, heroName]
    const filesInPortraitDir = onlyFiles.filter((entry) => startsWithSegments(entry, portraitDir))

    for (const entry of filesInPortraitDir) {
      const relativeSegments = entry.segments.slice(portraitDir.length)
      if (relativeSegments.length === 0) continue
      instructions.push({
        type: 'copy',
        source: entry.source,
        destination: toDestinationPath(context, [...heroPath, `${heroName}${heroSuffix}`, ...relativeSegments]),
      })
      assigned.add(entry.source)
    }

    for (const entry of onlyFiles) {
      if (assigned.has(entry.source) || !sameParentDirectory(entry, portrait)) continue
      instructions.push({
        type: 'copy',
        source: entry.source,
        destination: toDestinationPath(context, [...heroPath, ...entry.segments]),
      })
      assigned.add(entry.source)
    }
  }

  return instructions
}

function buildDirectoryNoProjectEntries(context: IExtensionContext, entries: FileEntry[]): CopyInstruction[] {
  const onlyFiles = entries.filter(hasFileExtension)
  const instructions: CopyInstruction[] = []
  const assigned = new Set<string>()

  for (const entry of onlyFiles) {
    const gameDirIndex = findKnownGameDirectoryIndex(entry)
    if (gameDirIndex < 0) continue
    instructions.push({
      type: 'copy',
      source: entry.source,
      destination: toDestinationPath(context, entry.segments.slice(gameDirIndex)),
    })
    assigned.add(entry.source)
  }

  for (const entry of onlyFiles) {
    if (assigned.has(entry.source)) continue
    const heroesIndex = entry.segments.findIndex((segment) => segment.toLowerCase() === HEROES_ROOT)
    if (heroesIndex < 0) continue
    instructions.push({
      type: 'copy',
      source: entry.source,
      destination: toDestinationPath(context, entry.segments.slice(heroesIndex)),
    })
  }

  return instructions
}

function installDarkestDungeonNoProjectMod(
  context: IExtensionContext,
  files: string[],
  stagingPath?: string
): { instructions: InstallInstruction[]; modType: string } {
  const entries = normalizeFiles(files)
  if (findProjectFiles(entries).length > 0) {
    return { instructions: [], modType: MOD_TYPE_ID }
  }

  const modName = inferNoProjectModName(context, entries, stagingPath)
  const noProjectEntries = entries.some((entry) => findKnownGameDirectoryIndex(entry) >= 0)
    ? buildDirectoryNoProjectEntries(context, entries)
    : buildHeroNoProjectEntries(context, entries)

  const instructions: InstallInstruction[] = noProjectEntries.map((instruction) => ({
    ...instruction,
    destination: path.join(modName, instruction.destination),
  }))

  instructions.push({
    type: 'generatefile',
    data: buildProjectXml(modName),
    destination: path.join(modName, PROJECT_XML),
  })

  return { instructions, modType: MOD_TYPE_ID }
}

async function main(context: IExtensionContext): Promise<void> {
  context.registerGame({
    id: GAME_ID,
    name: GAME_NAME,
    shortName: GAME_NAME,
    executable: EXECUTABLE,
    queryPath: () => findGame(context),
    modPath: MODS_DIR,
    modPathIsRelative: true,
    requiredFiles: [EXECUTABLE],
    environment: {
      SteamAPPId: String(GAME_ID),
    },
    details: {
      steamAppId: GAME_ID,
    },
  })

  context.registerModType(
    MOD_TYPE_ID,
    MOD_TYPE_PRIORITY,
    (gameId: number | string) => Number(gameId) === GAME_ID,
    () => path.join('{gamePath}', MODS_DIR),
    () => Promise.resolve(false),
    { name: GAME_NAME },
  )

  context.registerInstaller(
    MOD_TYPE_ID,
    INSTALLER_PRIORITY,
    testDarkestDungeonMod,
    (files, stagingPathOrOptions, maybeOptions) => {
      const stagingPath = typeof stagingPathOrOptions === 'string' ? stagingPathOrOptions : undefined
      const options = typeof stagingPathOrOptions === 'string' ? maybeOptions : stagingPathOrOptions
      return installDarkestDungeonMod(context, files, stagingPath, options)
    }
  )

  context.registerInstaller(
    MOD_TYPE_ID,
    NO_PROJECT_INSTALLER_PRIORITY,
    testDarkestDungeonNoProjectMod,
    (files, stagingPathOrOptions) => {
      const stagingPath = typeof stagingPathOrOptions === 'string' ? stagingPathOrOptions : undefined
      return installDarkestDungeonNoProjectMod(context, files, stagingPath)
    }
  )
}

export default main
